[project]
name = "005-agent-with-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
]

[project.optional-dependencies]
dev = [
    "python-lsp-server[all]>=1.7.0",
    "pylsp-rope>=0.1.11",
]
